[package]
name = "play"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
common.path = "../../common"
futures-channel = "0.3.31"
futures-util = "0.3.31"
leptos.workspace = true
leptos_meta.workspace = true
leptos_router.workspace = true
leptos-use.workspace = true
serde.workspace = true
stylance.workspace = true
wasm-bindgen.workspace = true
web-sys = "*"

[build-dependencies]
stylance-cli.workspace = true
