[package]
name = "server"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
axum = "0.8.8"
figment = { version = "0.10.19", features = ["env", "yaml"] }
leptos.workspace = true
leptos_axum = "0.8.7"
leptos_router.workspace = true
leptos-use.workspace = true
serde.workspace = true
shared.path = "../shared"
tokio = { version = "1", features = ["rt-multi-thread"] }

[features]
ssr = ["leptos/ssr", "leptos_router/ssr", "leptos-use/ssr"]
