games:
  - id: "yume"
    name: "Yume Nikki"
    permission: Yume1kki
  - id: "2kki"
    name: "Yume 2kki"
    permission: Yume2kki
  - id: "flow"
    name: ".flow"
  - id: "unevendream"
    name: "Uneven Dream"
  - id: "deepdreams"
    name: "Deep Dreams"
  - id: "prayers"
    name: "Answered Prayers"
  - id: "someday"
    name: "Someday"
  - id: "amillusion"
    name: "Amillusion"
  - id: "braingirl"
    name: "Braingirl"
  - id: "muma"
    name: "Muma|Rope"
  - id: "genie"
    name: "Dream Genie"
  - id: "mikan"
    name: "Mikan Muzou"
  - id: "ultraviolet"
    name: "Ultraviolet"
  - id: "sheawaits"
    name: "She Awaits"
  - id: "oversomnia"
    name: "Oversomnia"
  - id: "tsushin"
    name: "Yume Tsushin"
  - id: "nostalgic"
    name: "NostAlgic"
  - id: "oneshot"
    name: "OneShot"
  - id: "if"
    name: "If"
  - id: "unaccomplished"
    name: "Unaccomplished"
  - id: "fog"
    name: "FOG"
  - id: "cold"
    name: "[COLD]"
  - id: "loveyou"
    name: "loveyou"