Noil-menu26:
  game: 2kki
  gradient: linear-gradient(to bottom, rgb(37, 84, 140) 0 25%, rgb(44, 96, 144) 25% 37.5%, rgb(50, 106, 160) 37.5% 43.75%, rgb(55, 118, 177) 43.75% 50%, rgb(62, 129, 192) 50% 56.25%, rgb(79, 139, 198) 56.25% 62.5%, rgb(96, 150, 203) 62.5% 68.75%, rgb(102, 166, 217) 68.75% 75%, rgb(102, 189, 217) 75% 81.25%, rgb(102, 205, 217) 81.25% 87.5%, rgb(120, 239, 242) 87.5% 93.75%, rgb(154, 255, 255) 93.75% 100%, rgb(255, 255, 255) 100% 100%)
