# Changing this file at all causes all themes to be recompiled.

2kki:
  - system1
  - system2
  - system3
  - system4
  - system5
  - system0
  - systemyaguruma
  - systemrenge
  - system-b
  - system-g
  - system-i
  - system-iiii2
  - system-k
  - system-n
  - system-o
  - system-r
  - system-hw
  - system_Ca0
  - system_Ca0_old
  - Yeris_System_Rainbow
  - system_Suzume_choco
  - menu 20
  - menu 21
  - 2i9_sys1
  - 2i9_sys2
  - 2i9_sys3
  - Noil-menu25
  - Noil-menu26
  - Noil-menu27
  - RioSystem1-28
  - RioSystem2-29
  - Nuaahs_menu
  - RioSystem3
  - RioSystem4
  - system_nantai_33
  - system_Nulsdodage_Digital
  - system-lav
  - Kon_sys_1
  - Kon_sys_2
  - 2i9_sys4
  - system_mobile
  - Nulsdodage_Mono
  - Kon_sys_3
  - Kon_sys_4
  - Kon_sys_5
  - Kon_sys_6
  - RioSystem5
  - system_GBlike
  - horatsuki sys1
  - yumehako-sys1
  - sniperbob_system44
  - sniperbob_system45
  - moka_sys
  - 21keb_sys_1
  - JIVV_sys sakura
  - JIVV_sys dusk
  - Kong_Gothic window_system
  - takikomi_syst1
  - maptsukiSystem
  - yumehako-sys2
  - autumn_sys_rose
  - miau_system_diamond
  - Stheven_JIVV_Rainbow_Plateau
  - System_del_1
  - System_del_2
  - PGR_SYS_01
  - sweet_medical_utopia_menu_theme
  - 61024_sys1
  - kamara_sys_67
  - kamara_sys_68
  - kamara_sys_69
  - kamara_sys_70
  - mizkura_sys
  - uroyu_menu
  - PGR_SYS_02
  - PGR_SYS_03
  - ROKU95_menu
  - yumehako-sys3
  - 2da_system_01
  - nadeko_cards
  - ob_sys1
  - talyis-City of Revival menu theme
  - kamara_sys_81
  - 1247-system82
  - Kong_Pizza_system
  - Kong_akai_hasami_system
  - akalog_system-1
  - akalog_system-2
  - akalog_system-3
  - PGR_SYS_04
  - 710_sys_hal
  - fumosystem_neonhighway
  - fumosystem_diceruler
  - fumosystem_shrimp
  - fumosystem_comfort
  - System_del_3
  - Bean_sys1
  - Bean_sys2
  - awind_sus1
  - dizzy_spiral_menu_theme
  - Colby_LushSys
  - Colby_GlitchedSys
  - Colby_RadiantSys
  - PGR_SYS_05
  - takikomi_syst2
  - fluxide_sysblava
  - Holdery_Sys_Garden_Festival
  - system_E_eye
  - System_kuraud
  - Kong_SystemFC
  - natl_sys_PinkRibbon
  - aediorugap_sys
  - natl_sys2_NeonPink
  - natl_sys3_NeonBlue
amillusion:
  - fleur-2
  - fleur
  - bullemenu
  - menulabyrinthe
  - rosas menu
  - system EPACSE
  - MenuChance
  - tournesol
braingirl:
  - analog
  - Vanilla
  - Licorice
  - Tobacco
  - Chalkboard
  - Acryllic
  - Copper
  - Psychedelic
  - Spacecraft
  - Floorgum
  - moss
  - Carpet
  - Raspberry
cold:
  - system_F_1
  - system_F
  - system_C
  - system_R
  - system_FC
  - system_FC_1
unconscious:
  - system
  - system2
  - maple-penmenu
  - millie_system_sun
  - nacre_system_dusk
  - nacre_system_vague_memory
  - nacre_system_squids
  - bWF5_system_willow
  - delly_system_blue
  - delly_horrid
  - nacre_system_ammolites
  - roninnozlo_Menu_FILM
  - rollaby_system_mural
  - rollaby_system_mural_NEON
  - nacre_system_alter
  - orchidmantis_system_glowing
  - orchidmantis_system_sunset
  - orchidmantis_system_celestial
  - tcr_menu_sweet
  - voxlalien_system_c64
  - somnium_system_void
  - Mooncaller_system_gbc
  - delly_system_brickgem
  - dohus_system_golfer
  - delly_system_virtual
  - orchidmantis_system_orchid
  - orchidmantis_system_streetlight
  - orchidmantis_system_basalt
  - delly_system_metal
  - delly_system_redblack
  - MAMBACHROMATICSYSTEM
  - nacre_mossylab
  - claemon_system_crystal
  - delly_system_moth
  - cicada_system_toothdecay
  - umbrakinetic_system_coffee
  - claemon_system_aztec
  - delly_system_rainbow
  - dohus_system_oracle
  - delly_system_vacations
  - delly_system_moon
  - Delly_Dormouse_Polkadots_Menu theme
  - carson_system_picnic_a
  - carson_system_picnic_b
  - raptarr_system_eyeball
  - tako_system_butterfly
  - bas_chromatic_apparition
  - eviled_system_neone
  - maple-shamblingmenu
  - rollaby_system_chess
  - witblos_hlamenutheme
  - delly_system_green
  - rollaby_system_bleeding
  - rollaby_system_heart
  - messier_system_roots
  - angler_suncarved
  - erichtho_system_entrails
  - folly_system_tabitha
  - raptarr_system_vending
  - redo_sysBeloved
  - MorrySonando_Dudetastic_Visera_Menu theme
  - MorrySonando_Tender_Carnis_Menu theme
  - pats_system_unicorn
  - folly_system_lovely
deepdreams:
  - system_sterling
  - system_arabian
  - system_crystalline
  - system_kaleidoscope
  - system_rainbow
  - system_spiderlily
flow:
  - system
  - FCシムテム
  - systemdot
  - systemorange
  - system flower
  - system sugar
  - system rust
  - system smile
fog:
  - FOG_System
  - FOG_System_0001
  - FOG_System_0002
genie:
  - system_Negtive
  - system_Home
  - system_Springs
if:
  - sys-p
  - sys-p2
  - sys-p3
mikan:
  - s_1
  - s_2
  - s_3
muma:
  - SYSTEM
nostalgic:
  - imgbb4a4979529eec5
  - cute
  - mono
  - colorful
  - 001
  - 006
oneshot:
  - system
  - system2
  - System3
oversomnia:
  - window-a
  - window-b
  - window-c
  - window-d
  - window-e
  - window-f
  - window-g
  - window-h
  - window-i
  - window-j
  - window-temp1
prayers:
  - grey-and-chartreuse
  - chartreuse
  - customsystem
sheawaits:
  - system_sa1
  - system_stripedpink
  - system_rose
  - system_diamond
  - system_stripedviolet
  - system_garden
  - system_starrynight
  - system_stripedblue
  - system_sunset
  - system_heartglass
someday:
  - green
  - blue
  - turquoise
  - clock
  - threeoneone
  - 8bit
  - edible
  - rainbow
  - gold
  - swaltz
  - zapnef
  - monochrome_mk2
  - monochrome
tsushin:
  - SystemM
  - System
  - SystemB
  - SystemC
  - SystemD
  - SystemF
  - SystemP
  - SystemS
  - SystemW
ultraviolet:
  - ss-システムviolet
  - ss-システムmonochrome
  - ss-システムsilver
  - ss-システムorange
  - ss-システムcookie
  - ss-システムhexe
  - ss-システムhexe 2
  - ss-システムold black
  - ss-システムold  blue
  - ss-システムviolet II
  - ss-システムgreen
  - ss-システムeyes
  - ss-システムviolet III
unaccomplished:
  - system_N
  - system_EEE
  - system_0
  - OLD_system_0
  - system_Down
  - system_BL
  - system_ComP_BW
  - system_PC
  - system_ComP
  - system_ComP_Red
  - system_ComP_Halloween
  - system_ComP_PT
  - system_icea
unevendream:
  - 1247-0
  - 1247-0t
  - 1247-0k
  - 1247-01
  - 1247-02
  - 1247-03
  - 1247-04
  - 1247-pc98
  - EBroxas_menu_1
  - sekiranun_menutype01
  - lapis_menu_1
  - lysenthe_system
yume:
  - "0000000000009"
  - "0000000000010"
  - "0000000000011"
