[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos.workspace = true
leptos_meta.workspace = true
leptos_router.workspace = true
serde.workspace = true

# browser dependencies
console_error_panic_hook = { version = "0.1", optional = true }
wasm-bindgen = { version = "=0.2.106", optional = true }
stylance = { version = "0.7.4" }
web-sys = { version = "*", features = ["DomRect"] }

[features]
hydrate = ["dep:console_error_panic_hook", "dep:wasm-bindgen", "leptos/hydrate"]
ssr = ["leptos/ssr", "leptos_meta/ssr", "leptos_router/ssr"]

[build-dependencies]
stylance-cli = "0.7.4"
