[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos.workspace = true
leptos_meta = "0.8.5"
leptos_router.workspace = true
leptos-use = "0.17.0"
serde.workspace = true
stylance = { version = "0.7.4" }

# browser dependencies
console_error_panic_hook = { version = "0.1", optional = true }
wasm-bindgen = "=0.2.106"
web-sys = "*"

[features]
hydrate = ["dep:console_error_panic_hook", "leptos/hydrate"]
ssr = ["leptos/ssr", "leptos_meta/ssr", "leptos_router/ssr", "leptos-use/ssr"]

[build-dependencies]
stylance-cli = "0.7.4"
